//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 10:51:36 AM CEST 
//


package org.diagnoser.model.xml.compact.hazid;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.diagnoser.model.xml.compact.hazid package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.diagnoser.model.xml.compact.hazid
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Implication }
     * 
     */
    public Implication createImplication() {
        return new Implication();
    }

    /**
     * Create an instance of {@link Cause }
     * 
     */
    public Cause createCause() {
        return new Cause();
    }

    /**
     * Create an instance of {@link Deviation }
     * 
     */
    public Deviation createDeviation() {
        return new Deviation();
    }

    /**
     * Create an instance of {@link Tablerow }
     * 
     */
    public Tablerow createTablerow() {
        return new Tablerow();
    }

    /**
     * Create an instance of {@link Procedurehazidtable }
     * 
     */
    public Procedurehazidtable createProcedurehazidtable() {
        return new Procedurehazidtable();
    }

}
